#------------------------------------------------------
# Copyright (c) 2025, Elehobica
# Released under the BSD-2-Clause
# refer to https://opensource.org/licenses/BSD-2-Clause
#------------------------------------------------------

name: 'build-pico'
author: 'elehobica'
description: 'Build for Raspberry Pi Pico series'

inputs:
  path:
    description: 'Path to the CMakeLists.txt'
    required: false
    default: '.'
  jobs:
    description: 'Nuber of jobs for make'
    required: false
    default: ''
  build:
    description: 'Build directory'
    required: false
    default: 'build'
  platform:
    description: 'Pico platform'
    required: false
    default: 'rp2040'
  board:
    description: 'Pico board'
    required: false
    default: 'pico'
  cmake_options:
    description: 'CMake options'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - --path
    - ${{inputs.path}}
    - --jobs
    - ${{inputs.jobs}}
    - --build
    - ${{inputs.build}}
    - --platform
    - ${{inputs.platform}}
    - --board
    - ${{inputs.board}}
    - --cmake_options
    - ${{inputs.cmake_options}}
