#------------------------------------------------------
# Copyright (c) 2025, Elehobica
# Released under the BSD-2-Clause
# refer to https://opensource.org/licenses/BSD-2-Clause
#------------------------------------------------------

name: Build All

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          sparse-checkout: ${{inputs.path}}
      - name: Build-pico
        uses: elehobica/build-pico@main
        with:
          path: ${{inputs.path}}
      - name: Build-pico2
        uses: elehobica/build-pico@main
        with:
          path: ${{inputs.path}}
          build: build2
          platform: rp2350
          board: pico2